"""add email and edad to usuarios_alchemy

Revision ID: cbc6416a9f58
Revises: 
Create Date: 2025-06-06 11:25:27.858134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbc6416a9f58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dvds')
    op.drop_table('prestamos')
    op.drop_table('revistas')
    op.drop_table('libros')
    op.drop_table('usuarios_biblioteca')
    op.add_column('usuarios_alchemy', sa.Column('edad', sa.Integer(), nullable=True))
    op.add_column('usuarios_alchemy', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'usuarios_alchemy', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios_alchemy', type_='unique')
    op.drop_column('usuarios_alchemy', 'email')
    op.drop_column('usuarios_alchemy', 'edad')
    op.create_table('usuarios_biblioteca',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('libros',
    sa.Column('id_material', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_paginas', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['catalogo_biblioteca.id_material'], name=op.f('libros_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_material'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('revistas',
    sa.Column('id_material', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_edicion', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_publicacion', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['catalogo_biblioteca.id_material'], name=op.f('revistas_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_material'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prestamos',
    sa.Column('id_item', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_prestamo', mysql.DATETIME(), nullable=False),
    sa.Column('fecha_devolucion', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_item'], ['catalogo_biblioteca.id_material'], name=op.f('prestamos_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['usuarios_biblioteca.id_usuario'], name=op.f('prestamos_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_item', 'id_user', 'fecha_prestamo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dvds',
    sa.Column('id_material', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duracion', mysql.FLOAT(), nullable=False),
    sa.Column('formato', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['catalogo_biblioteca.id_material'], name=op.f('dvds_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_material'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
